Repository YuKARLO15/Bulak-Smart-Connect-JS, pull requests merged in 2025-05, with the labels that each got.

#200 Luan
  bulak-smart-connect-js/src/NavigationComponents/NavSide.css
  bulak-smart-connect-js/src/NavigationComponents/NavSide.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/ApplicationForm.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/BirthCertificateDashboard.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/CTCBirthcertificate.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/CorrectionChildSex.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/CorrectionClericalError.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/DelayedAbove18.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/DelayedBelow18.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/DelayedOneParentForeigner.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/DelayedOutOfTown.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/FirstNameCorrection.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/MarriageLicenseApplication.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/AppointmentComponents/AppointemtForm.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/AppointmentComponents/QRCodeAppointment.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/QRCodeComponents/QR.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/UserDashboard/UserDashboard.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/WalkInComponents/WalkInDashBoard.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/WalkInComponents/WalkInDetails.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/WalkInComponents/WalkInForm.jsx
Labels: enhancement, frontend

#201 edit routes in birth certificate for birth
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminDashboard/AdminDashboard.jsx
  bulak-smart-connect-js/src/App.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/BirthCertificateDashboard.jsx
Labels: enhancement, frontend

#202 marriage license form, marriage cert upload, marriage license summary
  bulak-smart-connect-js/src/App.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/ApplicationContent.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/ApplicationData.js
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/MarraiageDashboard.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/MarriageCertificateApplication.css
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/MarriageCertificateApplication.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/MarriageCertificateForm/HusbandForm.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/MarriageCertificateForm/MarriageCertificateForm.css
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/MarriageCertificateForm/MarriageCertificateForm.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/MarriageCertificateForm/MarriageLicenseSummary.css
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/MarriageCertificateForm/MarriageLicenseSummary.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/MarriageCertificateForm/MarriageSummaryForm.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/MarriageCertificateForm/WifeForm.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/MarriageDashboard.css
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/MarriageLicenseApplication.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/RecentApplicationsComponent.jsx
Labels: enhancement, frontend

#203 Luan
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/ApplicationData.js
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/FileUpload.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/MarriageCertificateApplication.css
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/MarriageCertificateApplication.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/MarriageCertificateForm/MarriageCertificateForm.css
Labels: enhancement, frontend

#205 style: format code for better readability and consistency across mult…
  bsc-js-backend/src/modules/counter/entities/counter.entity.ts
  bsc-js-backend/src/modules/queue/dto/create-queue.dto.ts
  bsc-js-backend/src/modules/queue/dto/update-queue.dto.ts
  bsc-js-backend/src/modules/queue/entities/queue-details.entity.ts
  bsc-js-backend/src/modules/queue/entities/queue.entity.ts
  bsc-js-backend/src/modules/queue/queue.controller.ts
  bsc-js-backend/src/modules/queue/queue.gateway.ts
  bsc-js-backend/src/modules/queue/queue.module.ts
  bsc-js-backend/src/modules/queue/queue.service.ts
Labels: enhancement, backend

#206 feat: implement Admin Appointment Dashboard with calendar and appoint…
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminAppointmentDashboard/AdminAppointmentDashboard.css
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminAppointmentDashboard/AdminAppointmentDashboard.jsx
  bulak-smart-connect-js/src/App.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/MarriageDashboard.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/RequirementMarriageList.css
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/RequirementMarriageList.jsx
Labels: enhancement, frontend

#207 Refactored some Github Actions
  .github/workflows/browser-compatibility.yml
  .github/workflows/e2e-test.yml
  bulak-smart-connect-js/src/setupTests.js
  bulak-smart-connect-js/vitest.config.js
Labels: github_actions

#208 feat: add react-scan for enhanced debugging capabilities
  bulak-smart-connect-js/package-lock.json
  bulak-smart-connect-js/package.json
  bulak-smart-connect-js/src/main.jsx
Labels: dependencies, frontend

#209 Yu2
  .github/workflows/api-security.yaml
Labels: github_actions

#210 feat: add RequirementMarriageList route and update ApplicationContent…
  bulak-smart-connect-js/src/App.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/ApplicationContent.jsx
Labels: enhancement, frontend

#211 Yu2
  bulak-smart-connect-js/package-lock.json
  bulak-smart-connect-js/package.json
  bulak-smart-connect-js/src/UserBulakSmartConnect/WalkInComponents/WalkInDashBoard.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/WalkInComponents/WalkInForm.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/WalkInComponents/WalkInQueueList.jsx
  bulak-smart-connect-js/src/services/queueService.js
Labels: enhancement, frontend

#212 admin preview application
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminApplicationComponents/AdminApplicationDetails.jsx
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminApplicationComponents/AdminMarriageLicensePreview.css
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminApplicationComponents/AdminMarriageLicensePreview.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/MarriageCertificateApplication.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/MarriageCertificateForm/MarriageCertificateForm.css
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/MarriageCertificateForm/MarriageSummaryForm.jsx
Labels: enhancement, frontend

#213 Queue Implementation on frontend
  bulak-smart-connect-js/src/UserBulakSmartConnect/WalkInComponents/WalkInDashBoard.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/WalkInComponents/WalkInForm.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/WalkInComponents/WalkInQueueList.jsx
  bulak-smart-connect-js/src/context/AuthContext.jsx
  bulak-smart-connect-js/src/services/api.js
Labels: enhancement, frontend

#214 Admin Post Announcement fix width (FEED)
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminAnnouncementComponents/AdminAnnouncement.css
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminAnnouncementComponents/AnnouncementFeed.css
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminAnnouncementComponents/AnnouncementForm.css
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminAnnouncementComponents/AnnouncementForm.jsx
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminAnnouncementComponents/AnnouncementPost.css
Labels: enhancement, frontend

#215 application status note visible to user
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminApplicationComponents/ApplicationAdminDashboard.css
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminApplicationComponents/ApplicationAdminDashboard.jsx
  bulak-smart-connect-js/src/NavigationComponents/NavSide.css
  bulak-smart-connect-js/src/NavigationComponents/NavSide.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/BirthApplicationSummary.css
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/BirthApplicationSummary.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/MarriageCertificateForm/MarriageSummaryForm.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/RecentApplicationsComponent.jsx
Labels: enhancement, frontend

#216 feat: Implement sidebar navigation and responsive design for Admin Da…
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminAppointmentDashboard/AdminAppointmentDashboard.css
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminAppointmentDashboard/AdminAppointmentDashboard.jsx
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminDashboard/AdminDashboard.css
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminDashboard/AdminDashboard.jsx
Labels: enhancement, frontend

#220 fixed widdth admin dashboard
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminAppointmentDashboard/AdminAppointmentDashboard.css
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminDashboard/AdminDashboard.css
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminDashboard/AdminDashboard.jsx
  bulak-smart-connect-js/src/NavigationComponents/NavSide.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/BirthApplicationSummary.jsx
Labels: enhancement

#221 feat: add @vitejs/plugin-react-swc for improved build performance
  bulak-smart-connect-js/package-lock.json
  bulak-smart-connect-js/package.json
  bulak-smart-connect-js/vite.config.js
Labels: enhancement, dependencies, frontend

#222 feat: implement Admin Walk-In Details and Queue components with styling
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminWalkInDetails/AdminWalkInDetails.css
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminWalkInDetails/AdminWalkInDetails.jsx
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminWalkInQueue/AdminWalkInQueue.css
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminWalkInQueue/AdminWalkInQueue.jsx
Labels: enhancement

#223 Github Actions
  .github/workflows/api-security.yaml
  .github/workflows/browser-compatibility.yml
  .github/workflows/ci.yml
  .github/workflows/code-quality-security.yml
  .github/workflows/dependency-security-scan.yml
  .github/workflows/e2e-test.yml
  .github/workflows/firebase-test.yml
  .github/workflows/mysql-ci.yml
  bsc-js-backend/src/auth/auth.controller.spec.ts
  bsc-js-backend/src/auth/auth.service.spec.ts
Labels: enhancement, github_actions, backend

#224 90% Admin Account Management
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AccountManagementComponents/AccountManagement.jsx
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AccountManagementComponents/NewUserInfo.js
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AccountManagementComponents/UserTable.css
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AccountManagementComponents/UserTable.jsx
Labels: enhancement, frontend

#228 Github Actions
  .github/workflows/api-documentation.yml
  .github/workflows/browser-compatibility.yml
  .github/workflows/frontend-documentation.yml
  .github/workflows/mysql-ci.yml
  bsc-js-backend/generate-hash.js
  bsc-js-backend/src/app.controller.ts
  bulak-smart-connect-js/styleguide.config.js
Labels: github_actions

#230 feat: enhance AdminWalkInDetails component with improved layout and f…
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminWalkInDetails/AdminWalkInDetails.css
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminWalkInDetails/AdminWalkInDetails.jsx
Labels: enhancement

#237 Yu2
  .github/workflows/frontend-documentation.yml
  bulak-smart-connect-js/scripts/generateStories.js
Labels: github_actions, frontend

#239 Modify form in all birth certificate type
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/BirthApplicationSummary.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/BirthCertificateDashboard.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/BirthCertificateForm.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/BirthCertificateForm/CopyBirthCertificate.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/CTCBirthcertificate.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/DelayedAbove18.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/DelayedOutOfTown.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/FileUpload.jsx
Labels: enhancement

#241 feat: integrate NavBar component and clean up sidebar code in AdminWa…
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminAppointmentDashboard/AdminAppointmentDashboard.jsx
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminDashboard/AdminDashboard.css
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminWalkInDetails/AdminWalkInDetails.jsx
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminWalkInQueue/AdminWalkInQueue.css
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminWalkInQueue/AdminWalkInQueue.jsx
Labels: enhancement

#242 changed: logo and title of the web page
  bulak-smart-connect-js/index.html
  bulak-smart-connect-js/public/BulakLGULogo.png
  bulak-smart-connect-js/public/BulakLGULogo.svg
Labels: enhancement, frontend

#244 Fix bug in nav bar dashboard
  bulak-smart-connect-js/src/NavigationComponents/NavBar.jsx
Labels: enhancement

#251 Edit side nav css
  bulak-smart-connect-js/src/NavigationComponents/NavSide.css
  bulak-smart-connect-js/src/NavigationComponents/NavSide.jsx
Labels: frontend

#252 Edited application admin
  bulak-smart-connect-js/package-lock.json
  bulak-smart-connect-js/package.json
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminApplicationComponents/ApplicationAdminDashboard.css
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminApplicationComponents/ApplicationAdminDashboard.jsx
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminChartsComponent/ApplicationLineChart.css
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminChartsComponent/ApplicationLineChart.jsx
Labels: enhancement

#254 improved recent application css
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/RecentApplicationsComponent.css
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/RecentApplicationsComponent.jsx
Labels: enhancement

#256 Refactor code for improved readability and consistency
  bsc-js-backend/src/app.module.ts
  bsc-js-backend/src/auth/auth.controller.spec.ts
  bsc-js-backend/src/auth/auth.controller.ts
  bsc-js-backend/src/auth/auth.service.spec.ts
  bsc-js-backend/src/auth/auth.service.ts
  bsc-js-backend/src/auth/dto/register.dto.ts
  bsc-js-backend/src/auth/guards/roles.guard.ts
  bsc-js-backend/src/auth/jwt.strategy.ts
  bsc-js-backend/src/main.ts
  bsc-js-backend/src/modules/queue/queue.controller.ts
  bsc-js-backend/src/modules/queue/queue.gateway.ts
  bsc-js-backend/src/modules/queue/queue.module.ts
  bsc-js-backend/src/modules/queue/queue.service.ts
  bsc-js-backend/src/users/entities/user.entity.ts
Labels: enhancement, backend

#259 Enhance bundle analysis and reporting workflows
  .github/workflows/code-quality-security.yml
  bulak-smart-connect-js/package-lock.json
  bulak-smart-connect-js/package.json
  bulak-smart-connect-js/vite.config.js
Labels: enhancement, github-actions, backend, frontend

#261 marriage modify function done
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/ApplicationData.js
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/MarriageCertificateForm/MarriageCertificateForm.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/MarriageCertificateForm/MarriageLicenseSummary.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/MarriageCertificateForm/MarriageSummaryForm.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/MarriageCertificateForm/WifeForm.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/RecentApplicationsComponent.jsx
Labels: enhancement

#265 Enhance user and queue management with new fields and SQL updates
  bsc-js-backend/src/modules/queue/dto/create-queue.dto.ts
  bsc-js-backend/src/modules/queue/entities/queue-details.entity.ts
  bsc-js-backend/src/modules/queue/queue.service.ts
  bulak-smart-connect-js/src/UserBulakSmartConnect/UserDashboard/UserDashboard.jsx
  database/modified-queuedetails-table-051525-v7/Dump20250515_QueueDetails_Table_Modified.sql
  database/modified-user-table-050825-v5/Dump20250508_User_Table_Modified.sql
  database/modified-user-table-050825-v5/Dump20250515_QueueDetails_Table_Modified.sql
  database/modified-user-table-v2-051325-v6/Dump20250513_User_Table_Modified_V2.sql
Labels: bug, enhancement, backend

#266 connected to database to walk-in
  bulak-smart-connect-js/src/UserBulakSmartConnect/WalkInComponents/WalkInForm.jsx
Labels: enhancement

#268 fixed bug in walk in
  bulak-smart-connect-js/src/UserBulakSmartConnect/WalkInComponents/WalkInForm.jsx
Labels: enhancement

#270 Enhance queue creation and user identification logic
  bsc-js-backend/src/modules/queue/queue.controller.ts
  bulak-smart-connect-js/src/UserBulakSmartConnect/WalkInComponents/WalkInForm.jsx
  bulak-smart-connect-js/src/services/queueService.js
Labels: enhancement, backend

#272 walk in queue in admin dashboard ( still neen to get details )
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminDashboard/AdminDashboard.jsx
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminDashboard/WalkInQueueAdmin.css
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminDashboard/WalkInQueueAdmin.jsx
  bulak-smart-connect-js/src/services/queueService.js
Labels: enhancement

#273 Yu2
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminDashboard/WalkInQueueAdmin.jsx
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminWalkInDetails/AdminWalkInDetails.jsx
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminWalkInQueue/AdminWalkInQueue.jsx
  bulak-smart-connect-js/src/App.jsx
  bulak-smart-connect-js/src/services/queueService.js
Labels: bug, enhancement, backend

#280 Astria
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminAppointmentDashboard/AdminAppointmentDashboard.css
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminAppointmentDashboard/AdminAppointmentDashboard.jsx
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminAppointmentDashboard/AllAppointmentAdmin.css
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminAppointmentDashboard/AllAppointmentsAdmin.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/MarriageCertificateForm/MarriageCertificateForm.css
Labels: enhancement

#283 User Accounts
  bulak-smart-connect-js/src/App.jsx
  bulak-smart-connect-js/src/NavigationComponents/NavSide.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/UserAccountSettings/UserAccount.css
  bulak-smart-connect-js/src/UserBulakSmartConnect/UserAccountSettings/UserAccount.jsx
Labels: enhancement

#285 add side nav in user accounts
  bulak-smart-connect-js/src/UserBulakSmartConnect/UserAccountSettings/UserAccount.css
  bulak-smart-connect-js/src/UserBulakSmartConnect/UserAccountSettings/UserAccount.jsx
Labels: enhancement

#288 Refactor appointment management and integrate real-time availability
  bulak-smart-connect-js/src/UserBulakSmartConnect/AppointmentComponents/AppointmentContent.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/AppointmentComponents/RecentAppointment.jsx
  bulak-smart-connect-js/src/services/appointmentService.js
Labels: enhancement, backend, frontend

#289 appointment enchanced
  bulak-smart-connect-js/src/UserBulakSmartConnect/AppointmentComponents/AppointmentContent.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/AppointmentComponents/QRCodeAppointment.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/AppointmentComponents/QrCodeAppointment.css
Labels: enhancement

#291 Add announcement module with CRUD functionality and validation
  bsc-js-backend/src/app.module.ts
  bsc-js-backend/src/modules/announcement/announcement.controller.spec.ts
  bsc-js-backend/src/modules/announcement/announcement.controller.ts
  bsc-js-backend/src/modules/announcement/announcement.module.ts
  bsc-js-backend/src/modules/announcement/announcement.service.spec.ts
  bsc-js-backend/src/modules/announcement/announcement.service.ts
  bsc-js-backend/src/modules/announcement/dto/create-announcement.dto.ts
  bsc-js-backend/src/modules/announcement/dto/update-announcement.dto.ts
  bsc-js-backend/src/modules/announcement/entities/announcement.entity.ts
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminAnnouncementComponents/AdminAnnouncement.jsx
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminAnnouncementComponents/AnnouncementForm.jsx
  bulak-smart-connect-js/src/services/announcementService.js
  database/create-announcement-table-052525-v9/Dump20250525_Create_Announcement_Table.sql
Labels: enhancement, backend, frontend

#293 Luan
  bulak-smart-connect-js/src/LandingPageComponents/LandingPage.css
  bulak-smart-connect-js/src/LandingPageComponents/LandingPage.jsx
  bulak-smart-connect-js/src/LandingPageComponents/LandingPageAssets/HeroBg.JPEG
Labels: enhancement

#296 Add mock repositories and update login payload
  .github/workflows/mysql-ci.yml
  bsc-js-backend/src/modules/announcement/announcement.controller.spec.ts
  bsc-js-backend/src/modules/announcement/announcement.service.spec.ts
  bsc-js-backend/src/modules/appointment/appointment.controller.spec.ts
  bsc-js-backend/src/modules/appointment/appointment.service.spec.ts
Labels: github-actions, backend

#297 Add unit tests for Queue, Queues, and Roles components
  bsc-js-backend/src/modules/queue/queue.controller.spec.ts
  bsc-js-backend/src/modules/queue/queue.gateway.spec.ts
  bsc-js-backend/src/modules/queue/queue.service.spec.ts
  bsc-js-backend/src/modules/queue/queues.controller.spec.ts
  bsc-js-backend/src/roles/roles.controller.spec.ts
  bsc-js-backend/src/roles/roles.service.spec.ts
Labels: enhancement, backend

#298 Update README with backend tables and development scripts
  README.md
Labels: documentation

#299 Update Swagger logo URL in technology stack section of README.md
  README.md
Labels: documentation

#302 Enhance API documentation with Swagger details and guides
  README.md
  bsc-js-backend/src/main.ts
Labels: documentation, enhancement, backend

#304 Fixed data integration , and css for recent appointments and walk in …
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminDashboard/AdminDashboard.css
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminDashboard/RecentAppointmentsAdmin.css
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminDashboard/RecentAppointmentsAdmin.jsx
Labels: enhancement

#303 Integrate MinIO for document storage
  .github/workflows/backend-tests.yml
  README.md
  bsc-js-backend/package-lock.json
  bsc-js-backend/package.json
  bsc-js-backend/src/app.module.ts
  bsc-js-backend/src/main.ts
  bsc-js-backend/src/modules/announcement/announcement.service.ts
  bsc-js-backend/src/modules/announcement/entities/announcement.entity.ts
  bsc-js-backend/src/modules/document-applications/document-applications.controller.spec.ts
  bsc-js-backend/src/modules/document-applications/document-applications.controller.ts
  bsc-js-backend/src/modules/document-applications/document-applications.module.ts
  bsc-js-backend/src/modules/document-applications/document-applications.service.spec.ts
  bsc-js-backend/src/modules/document-applications/document-applications.service.ts
  bsc-js-backend/src/modules/document-applications/dto/create-document-application.dto.ts
  bsc-js-backend/src/modules/document-applications/dto/update-document-application.dto.ts
  bsc-js-backend/src/modules/document-applications/entities/application-status-history.entity.ts
  bsc-js-backend/src/modules/document-applications/entities/document-application.entity.ts
  bsc-js-backend/src/modules/document-applications/entities/document-file.entity.ts
  bsc-js-backend/src/modules/document-applications/services/minio.service.spec.ts
  bsc-js-backend/src/modules/document-applications/services/minio.service.ts
  bsc-js-backend/src/modules/queue/queue.controller.spec.ts
  bsc-js-backend/src/modules/queue/queue.gateway.spec.ts
  bsc-js-backend/src/modules/queue/queue.service.spec.ts
  bsc-js-backend/src/modules/queue/queues.controller.spec.ts
  bsc-js-backend/src/roles/roles.controller.spec.ts
  bsc-js-backend/src/roles/roles.service.spec.ts
  bsc-js-backend/src/services/minio.service.spec.ts
  bsc-js-backend/src/services/minio.service.ts
  bulak-smart-connect-js/eslint.config.js
  bulak-smart-connect-js/package.json
  bulak-smart-connect-js/src/services/documentApplicationService.js
  bulak-smart-connect-js/vite.config.js
  bulak-smart-connect-js/vitest.config.js
  database/create-document-applications-table-v10/Dump20250527_Create_Document_Applications_Table.sql
Labels: documentation, enhancement, github-actions, backend, frontend
