Repository YuKARLO15/Bulak-Smart-Connect-JS, pull requests merged in 2025-03, with the labels that each got.

#83 birthcertform. example only for routing
  bulak-smart-connect-js/src/App.jsx
  bulak-smart-connect-js/src/ApplicationComponents/BirthCertificateApplications/BirthCertificateApplicationData.js
  bulak-smart-connect-js/src/ApplicationComponents/BirthCertificateApplications/BirthCertificateDashboard.jsx
  bulak-smart-connect-js/src/ApplicationComponents/BirthCertificateApplications/BirthCertificateForm.css
  bulak-smart-connect-js/src/ApplicationComponents/BirthCertificateApplications/BirthCertificateForm.jsx
Labels: enhancement

#84 fixed dashboard css
  bulak-smart-connect-js/src/ApplicationComponents/RecentApplicationsComponent.css
  bulak-smart-connect-js/src/ApplicationComponents/RecentApplicationsComponent.jsx
  bulak-smart-connect-js/src/AppointmentComponents/RecentAppointment.css
  bulak-smart-connect-js/src/LogInComponents/LogIn.css
  bulak-smart-connect-js/src/UserDashboard/DashboardButtons.css
  bulak-smart-connect-js/src/UserDashboard/DashboardContent.css
  bulak-smart-connect-js/src/UserDashboard/UserDashboard.css
  bulak-smart-connect-js/src/UserDashboard/UserDashboard.jsx
Labels: enhancement

#86 Workflows
  .github/dependabot.yml
  .github/workflows/accessibility-testing.yml
  .github/workflows/api-documentation.yml
  .github/workflows/automatic-dependabot-update.yml
  .github/workflows/browser-compatibility.yml
  .github/workflows/ci.yml
  .github/workflows/code-quality-security.yml
  .github/workflows/codeql.yml
  .github/workflows/e2e-test.yml
  .github/workflows/firebase-test.yml
  .github/workflows/pr-check.yml
  bsc-js-backend/package.json
  bulak-smart-connect-js/a11y-report.md
  bulak-smart-connect-js/package-lock.json
  bulak-smart-connect-js/package.json
  bulak-smart-connect-js/src/__tests__/App.test.jsx
  bulak-smart-connect-js/src/__tests__/LogInCard.test.jsx
  bulak-smart-connect-js/src/setupTests.js
  bulak-smart-connect-js/vitest.config.js
Labels: documentation, enhancement

#91 Workflows
  .github/workflows/api-security.yaml
Labels: enhancement

#92 Improved Dependabot Workflow
  .github/dependabot.yml
  .github/workflows/automatic-dependabot-update.yml
  .github/workflows/dependency-security-scan.yml
Labels: enhancement, github_actions

#112 Birth form css fixed
  bulak-smart-connect-js/src/ApplicationComponents/BirthCertificateApplications/BirthCertificateDashboard.jsx
  bulak-smart-connect-js/src/ApplicationComponents/BirthCertificateApplications/BirthCertificateForm.css
  bulak-smart-connect-js/src/ApplicationComponents/BirthCertificateApplications/BirthCertificateForm.jsx
  bulak-smart-connect-js/src/ApplicationComponents/BirthCertificateApplications/BirthCertificateForm/ChildIdentifyingForm.jsx
  bulak-smart-connect-js/src/ApplicationComponents/BirthCertificateApplications/BirthCertificateForm/FatherIdentifyingForm.css
  bulak-smart-connect-js/src/ApplicationComponents/BirthCertificateApplications/BirthCertificateForm/FatherIdentifyingForm.jsx
  bulak-smart-connect-js/src/ApplicationComponents/BirthCertificateApplications/BirthCertificateForm/IdentifyingForm.css
  bulak-smart-connect-js/src/ApplicationComponents/BirthCertificateApplications/BirthCertificateForm/MarriageIdentifyingForm.css
  bulak-smart-connect-js/src/ApplicationComponents/BirthCertificateApplications/BirthCertificateForm/MarriageIdentifyingForm.jsx
  bulak-smart-connect-js/src/ApplicationComponents/BirthCertificateApplications/BirthCertificateForm/MotherIdentifyingForm.css
  bulak-smart-connect-js/src/ApplicationComponents/BirthCertificateApplications/BirthCertificateForm/MotherIdentifyingForm.jsx
Labels: enhancement

#114 Landing Page and Footer
  bulak-smart-connect-js/src/App.jsx
  bulak-smart-connect-js/src/LandingPageComponents/LandingPage.css
  bulak-smart-connect-js/src/LandingPageComponents/LandingPage.jsx
  bulak-smart-connect-js/src/LandingPageComponents/LandingPageAssets/BulakLGULogo.png
  bulak-smart-connect-js/src/LandingPageComponents/LandingPageAssets/DeviceMockUp.png
  bulak-smart-connect-js/src/LogInComponents/NavBar.css
  bulak-smart-connect-js/src/LogInComponents/NavBar.jsx
  bulak-smart-connect-js/src/UserDashboard/UserDashboard.css
  bulak-smart-connect-js/src/UserDashboard/UserDashboard.jsx
  bulak-smart-connect-js/src/footer.jsx
  bulak-smart-connect-js/src/main.jsx
Labels: enhancement

#116 Luan
  bulak-smart-connect-js/src/App.jsx
  bulak-smart-connect-js/src/ApplicationComponents/ApplicationContent.css
  bulak-smart-connect-js/src/ApplicationComponents/BirthCertificateApplications/BirthApplicationSummary.css
  bulak-smart-connect-js/src/ApplicationComponents/BirthCertificateApplications/BirthApplicationSummary.jsx
  bulak-smart-connect-js/src/ApplicationComponents/BirthCertificateApplications/BirthCertificateApplicationData.js
  bulak-smart-connect-js/src/ApplicationComponents/BirthCertificateApplications/BirthCertificateForm.css
  bulak-smart-connect-js/src/ApplicationComponents/BirthCertificateApplications/BirthCertificateForm.jsx
  bulak-smart-connect-js/src/ApplicationComponents/BirthCertificateApplications/CorrectionChildSex.jsx
  bulak-smart-connect-js/src/ApplicationComponents/BirthCertificateApplications/CorrectionClericalError.jsx
  bulak-smart-connect-js/src/ApplicationComponents/BirthCertificateApplications/DelayedAbove18.css
  bulak-smart-connect-js/src/ApplicationComponents/BirthCertificateApplications/DelayedAbove18.jsx
  bulak-smart-connect-js/src/ApplicationComponents/BirthCertificateApplications/DelayedBelow18.jsx
  bulak-smart-connect-js/src/ApplicationComponents/BirthCertificateApplications/DelayedOneParentForeigner.css
  bulak-smart-connect-js/src/ApplicationComponents/BirthCertificateApplications/DelayedOneParentForeigner.jsx
  bulak-smart-connect-js/src/ApplicationComponents/BirthCertificateApplications/DelayedOutOfTown.css
  bulak-smart-connect-js/src/ApplicationComponents/BirthCertificateApplications/DelayedOutOfTown.jsx
  bulak-smart-connect-js/src/ApplicationComponents/BirthCertificateApplications/FristNameCorrection.jsx
  bulak-smart-connect-js/src/ApplicationComponents/RecentApplications.js
  bulak-smart-connect-js/src/ApplicationComponents/RecentApplicationsComponent.css
  bulak-smart-connect-js/src/ApplicationComponents/RecentApplicationsComponent.jsx
  bulak-smart-connect-js/src/AppointmentComponents/AppoinmentForm.css
  bulak-smart-connect-js/src/AppointmentComponents/AppointmentContent.css
  bulak-smart-connect-js/src/AppointmentComponents/AppointmentContent.jsx
  bulak-smart-connect-js/src/AppointmentComponents/QRCodeAppointment.jsx
  bulak-smart-connect-js/src/AppointmentComponents/QrCodeAppointment.css
  bulak-smart-connect-js/src/LandingPageComponents/LandingPage.jsx
  bulak-smart-connect-js/src/SignUpComponents/SignUpForm.css
  bulak-smart-connect-js/src/UserDashboard/DashboardButtons.jsx
Labels: enhancement

#70 Backend Logic
  README.md
  bsc-js-backend/generate-hash.js
  bsc-js-backend/nest-cli.json
  bsc-js-backend/package-lock.json
  bsc-js-backend/package.json
  bsc-js-backend/src/app.module.ts
  bsc-js-backend/src/auth/auth.controller.spec.ts
  bsc-js-backend/src/auth/auth.controller.ts
  bsc-js-backend/src/auth/auth.module.ts
  bsc-js-backend/src/auth/auth.service.spec.ts
  bsc-js-backend/src/auth/auth.service.ts
  bsc-js-backend/src/auth/dto/login.dto.ts
  bsc-js-backend/src/auth/dto/register.dto.ts
  bsc-js-backend/src/auth/jwt-auth.guard.ts
  bsc-js-backend/src/auth/jwt.strategy.ts
  bsc-js-backend/src/config/database.config.ts
  bsc-js-backend/src/config/firebase.ts
  bsc-js-backend/src/main.ts
  bsc-js-backend/src/users/entities/user.entity.ts
  bsc-js-backend/src/users/users.module.ts
  bulak-smart-connect-js/.gitignore
  bulak-smart-connect-js/.prettierrc
  bulak-smart-connect-js/firebase.js
  bulak-smart-connect-js/package-lock.json
  bulak-smart-connect-js/package.json
  bulak-smart-connect-js/src/App.jsx
  bulak-smart-connect-js/src/AuthContext.jsx
  bulak-smart-connect-js/src/LandingPageComponents/LandingPage.jsx
  bulak-smart-connect-js/src/LogInComponents/LogIn.jsx
  bulak-smart-connect-js/src/LogInComponents/LogInCard.jsx
  bulak-smart-connect-js/src/PrivateRoute.jsx
  bulak-smart-connect-js/src/SignUpComponents/SignUpForm.jsx
  bulak-smart-connect-js/src/UserDashboard/NavBar.jsx
  bulak-smart-connect-js/src/main.jsx
  bulak-smart-connect-js/src/services/api.js
Labels: bug, documentation, enhancement
