Repository YuKARLO15/Bulak-Smart-Connect-JS, pull requests merged in 2025-06, with the labels that each got.

#308 Fix documentApplicationService integration and refactor component logic
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/BirthCertificateForm/CopyBirthCertificate.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/CTCBirthcertificate.jsx
Labels: enhancement, frontend

#311 fab button announcement landing page
  bulak-smart-connect-js/src/LandingPageComponents/FloatingAnnouncement.css
  bulak-smart-connect-js/src/LandingPageComponents/FloatingAnnouncement.jsx
  bulak-smart-connect-js/src/LandingPageComponents/LandingPage.css
  bulak-smart-connect-js/src/LandingPageComponents/LandingPage.jsx
  bulak-smart-connect-js/src/NavigationComponents/NavAssets/NavBulakLGU.png
  bulak-smart-connect-js/src/NavigationComponents/NavBar.css
  bulak-smart-connect-js/src/NavigationComponents/NavBar.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/AppointmentComponents/AppointmentContent.css
  bulak-smart-connect-js/src/UserBulakSmartConnect/AppointmentComponents/AppointmentContent.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/AppointmentComponents/DataPickerAppointmentForm.jsx
Labels: enhancement

#315 integration of FAB Announce in the announcement
  bulak-smart-connect-js/src/UserBulakSmartConnect/AppointmentComponents/AppointemtForm.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/AppointmentComponents/AppointmentContent.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/AppointmentComponents/AppointmentDashboard.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/AppointmentComponents/QRCodeAppointment.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/AppointmentComponents/QrCodeAppointment.css
  bulak-smart-connect-js/src/UserBulakSmartConnect/AppointmentComponents/RecentAppointment.jsx
Labels: enhancement

#316 feat: add PWA support with install prompt and offline indicators
  bulak-smart-connect-js/.gitignore
  bulak-smart-connect-js/index.html
  bulak-smart-connect-js/package-lock.json
  bulak-smart-connect-js/package.json
  bulak-smart-connect-js/src/App.jsx
  bulak-smart-connect-js/src/components/InstallPrompt.jsx
  bulak-smart-connect-js/src/components/OfflineIndicator.jsx
  bulak-smart-connect-js/src/hooks/usePWA.js
  bulak-smart-connect-js/vite.config.js
Labels: enhancement, frontend

#317 data privacy function
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/BirthCertificateDashboard.css
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/BirthCertificateDashboard.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/TermsAndConditionComponents/TermsAndCondition.jsx
Labels: enhancement

#320 Fix infinite loop in data loading logic
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/BirthApplicationSummary.jsx
Labels: bug, enhancement, frontend

#324 Add Admin Account management feature with profile editing and passwor…
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminAccount/AdminAccount.css
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminAccount/AdminAccount.jsx
  bulak-smart-connect-js/src/App.jsx
  bulak-smart-connect-js/src/NavigationComponents/NavSide.jsx
Labels: enhancement

#325 Implement localStorage management and enhance application status handling
  bulak-smart-connect-js/src/LogInComponents/LogIn.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/BirthApplicationSummary.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/CTCBirthcertificate.jsx
  bulak-smart-connect-js/src/services/localStorageManager.js
Labels: enhancement, frontend

#326 Refactor local storage handling in CopyBirthCertificate component
  bulak-smart-connect-js/src/App.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/BirthCertificateForm/CopyBirthCertificate.jsx
Labels: enhancement, frontend

#330 Refactor QueueController and fix meta tag typo
  bsc-js-backend/src/modules/queue/queue.controller.ts
  bulak-smart-connect-js/index.html
Labels: bug, enhancement, backend, frontend

#331 Refactor AdminWalkInDetails component and styles for improved layout …
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminWalkInDetails/AdminWalkInDetails.css
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminWalkInDetails/AdminWalkInDetails.jsx
Labels: enhancement

#334 Implement user management features with CRUD operations and statistics
  bsc-js-backend/src/users/dto/create-user.dto.ts
  bsc-js-backend/src/users/dto/paginated-users-response.dto.ts
  bsc-js-backend/src/users/dto/update-user-status.dto.ts
  bsc-js-backend/src/users/dto/user-query.dto.ts
  bsc-js-backend/src/users/dto/user-response.dto.ts
  bsc-js-backend/src/users/dto/user-stats-response.dto.ts
  bsc-js-backend/src/users/entities/user.entity.ts
  bsc-js-backend/src/users/users.controller.spec.ts
  bsc-js-backend/src/users/users.controller.ts
  bsc-js-backend/src/users/users.module.ts
  bsc-js-backend/src/users/users.service.spec.ts
  bsc-js-backend/src/users/users.service.ts
  bulak-smart-connect-js/src/services/documentApplicationService.js
  bulak-smart-connect-js/src/services/userService.js
  database/modified-user-table-v3-060625-v11/Dump20250606_Modify_User_Table_V2.sql
Labels: bug, enhancement, backend, frontend

#337 Update user form validation and role display names in AdminAddUser component
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AccountManagementComponents/AdminAddAccount.jsx
Labels: enhancement, frontend

#339 feat: Implement data privacy notice with user agreement handling in M…
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/MarriageDashboard.css
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/MarriageDashboard.jsx
Labels: enhancement

#336 • ApplicationDashbard ( admin )
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminApplicationComponents/AdminApplicationDetails.jsx
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminApplicationComponents/AdminCopyBirthPreview.css
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminApplicationComponents/AdminCopyBirthPreview.jsx
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminApplicationComponents/ApplicationAdminDashboard.css
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminApplicationComponents/ApplicationAdminDashboard.jsx
  bulak-smart-connect-js/src/NavigationComponents/NavSide.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/ApplicationContent.css
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/ApplicationContent.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/ApplicationForm.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/BirthCertificateDashboard.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/WalkInComponents/WalkInDashBoard.jsx
Labels: enhancement

#340 backend integration
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminApplicationComponents/AdminCopyBirthPreview.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/BirthCertificateDashboard.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/BirthCertificateForm.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/DelayedBelow18.jsx
Labels: enhancement

#341 integrated back end with birthcertificate preview in admin side
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminApplicationComponents/AdminApplicationDetails.jsx
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminDashboard/RecentApplicationsAdmin.css
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/BirthCertificateDashboard.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/BirthCertificateForm.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/CorrectionChildSex.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/CorrectionClericalError.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/DelayedOutOfTown.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/FirstNameCorrection.jsx
Labels: enhancement

#343 fixed css of delaed birh out of town file upload
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminApplicationComponents/AdminFilePreview.jsx
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminApplicationComponents/ApplicationAdminDashboard.css
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminApplicationComponents/ApplicationPieChart.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/BirthCertificateForm/MarriageIdentifyingForm.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/CTCBirthcertificate.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/DelayedAbove18.css
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/DelayedAbove18.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/DelayedOutOfTown.css
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/DelayedOutOfTown.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/MarriageCertificateForm/MarriageLicensePrint.css
Labels: enhancement

#346 Luan
  bulak-smart-connect-js/src/LandingPageComponents/LandingPage.css
  bulak-smart-connect-js/src/LandingPageComponents/LandingPage.jsx
  bulak-smart-connect-js/src/NavigationComponents/NavBar.css
  bulak-smart-connect-js/src/NavigationComponents/NavBar.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/BirthCertificateForm/RegularBirth.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/DelayedAbove18.css
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/DelayedBelow18.css
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/DelayedBelow18.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/DelayedOneParentForeigner.css
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/DelayedOneParentForeigner.jsx
Labels: enhancement

#347 Nav and download modification
  bulak-smart-connect-js/src/NavigationComponents/NavBar.css
  bulak-smart-connect-js/src/NavigationComponents/NavBar.jsx
  bulak-smart-connect-js/src/components/InstallPrompt.jsx
Labels: enhancement

#351 Integrate document application service and improve error handling
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/RecentApplicationsComponent.jsx
  bulak-smart-connect-js/src/services/documentApplicationService.js
Labels: enhancement, frontend

#350 birth certificate affidavit
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminApplicationComponents/AdminAffidavitDetails.css
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminApplicationComponents/AdminAffidavitDetails.jsx
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminApplicationComponents/AdminApplicationDetails.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/BirthCertificateForm/BirthBackIdentifyingForm.jsx
Labels: enhancement

#352 submit button disabled error in file submissions
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/DelayedAbove18.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/DelayedBelow18.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/DelayedOutOfTown.jsx
Labels: enhancement

#354 Change updateApplication method to use PATCH for partial updates
  bulak-smart-connect-js/src/services/documentApplicationService.js
Labels: bug, backend

#356 Enhance file upload and application status management
  bsc-js-backend/src/modules/document-applications/document-applications.service.ts
  bsc-js-backend/src/modules/document-applications/entities/application-status-history.entity.ts
  bsc-js-backend/src/modules/document-applications/entities/document-application.entity.ts
  bulak-smart-connect-js/src/services/documentApplicationService.js
  database/modified-application-status-history-061325-v12/Dump20250613_Modified_Application_Status_History.sql
  database/modified-document-applications-table-061325-v13/Dump20250613_Modified_Document_Applications_Table.sql
Labels: bug, enhancement, backend

#355 fetch application stat admin dashboard
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminApplicationComponents/AdminApplicationDetails.css
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminApplicationComponents/AdminApplicationDetails.jsx
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminDashboard/AdminDashboard.jsx
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminDashboard/RecentApplicationsAdmin.jsx
Labels: enhancement

#358 Astria
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/MarriageCertificateApplication.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/MarriageCertificateForm/MarriageAffidavitForm.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/MarriageCertificateForm/MarriageCertificateForm.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/MarriageLicenseApplication.jsx
  bulak-smart-connect-js/src/services/documentApplicationService.js
Labels: enhancement, frontend

#360 Enhance file upload sanitization and fix spelling in Marriage License application
  bsc-js-backend/src/modules/document-applications/services/minio.service.ts
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/MarriageLicenseApplication.jsx
  bulak-smart-connect-js/src/services/documentApplicationService.js
Labels: enhancement, backend

#362 Refactor file upload process by removing object name sanitization
  bsc-js-backend/src/modules/document-applications/services/minio.service.ts
Labels: bug, backend

#365 Implement appointment data fetching and enhance appointment handling
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminAppointmentDashboard/AdminAppointmentDashboard.jsx
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminAppointmentDashboard/AllAppointmentsAdmin.jsx
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AppointmentDetailsComponents/AppointmentDetails.css
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AppointmentDetailsComponents/AppointmentDetails.jsx
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AppointmentDetailsComponents/UserInfoCard.css
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AppointmentDetailsComponents/UserInfoCard.jsx
  bulak-smart-connect-js/src/App.jsx
Labels: enhancement, frontend

#363 MODIFICATIONS
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminAppointmentDashboard/AllAppointmentsAdmin.jsx
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminDashboard/RecentApplicationsAdmin.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/BirthCertificateDashboard.jsx
Labels: enhancement

#367 Add recent appointments functionality and date formatting
  bulak-smart-connect-js/src/UserBulakSmartConnect/AppointmentComponents/AppointmentContent.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/AppointmentComponents/RecentAppointment.jsx
Labels: bug, frontend

#368 Enhanced user queue fetching and management features
  bsc-js-backend/src/modules/queue/queue.service.ts
  bsc-js-backend/src/modules/queue/queues.controller.ts
  bulak-smart-connect-js/src/UserBulakSmartConnect/WalkInComponents/WalkInDashBoard.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/WalkInComponents/WalkInForm.jsx
  bulak-smart-connect-js/src/services/queueService.js
Labels: enhancement, backend, frontend

#369 Luan
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminApplicationComponents/AdminApplicationDetails.jsx
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminDashboard/RecentAppointmentsAdmin.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/BirthApplicationSummary.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/BirthCertificateDashboard.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/BirthCertificateForm/CopyBirthCertificate.jsx
Labels: enhancement

#370 fixed preview for clerical in the admin side
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminApplicationComponents/AdminApplicationDetails.jsx
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminApplicationComponents/AdminCopyBirthPreview.jsx
Labels: enhancement

#375 Luan
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminApplicationComponents/AdminAffidavitDetails.jsx
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminApplicationComponents/AdminApplicationDetails.jsx
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminApplicationComponents/AdminFilePreview.jsx
Labels: enhancement

#377 Enhance queue display with serving status and animations
  bulak-smart-connect-js/src/UserBulakSmartConnect/WalkInComponents/WalkInDashBoard.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/WalkInComponents/WalkInQueue.css
  bulak-smart-connect-js/src/UserBulakSmartConnect/WalkInComponents/WalkInQueueList.jsx
Labels: enhancement, frontend

#376 Refactor Marriage Certificate Form styles: Remove old CSS and add new…
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/MarriageCertificateForm/MarriageAffidavitForm.css
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/MarriageCertificateForm/MarriageAffidavitForm.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/MarriageCertificateForm/MarriageCertificateForm.css
Labels: enhancement

#382 Improve performance of data processing module
  .github/workflows/backend-tests.yml
  bsc-js-backend/package.json
  bsc-js-backend/src/users/users.service.spec.ts
  bsc-js-backend/test/jest-e2e.json
  bsc-js-backend/test/jest-setup-e2e.ts
  bsc-js-backend/test/jest-setup.ts
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminSmartQueueComponents/ScreenSmartQueue.jsx
Labels: enhancement, github-actions, backend, frontend

#386 Add GitHub Actions workflow for dashboard generation and deployment
  .github/workflows/update-dashboard.yml
Labels: enhancement, github-actions

#391 Luan
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/ApplicationContent.css
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/MarriageCertificateForm/MarriageCertificateForm.css
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/MarriageCertificateForm/MarriageCertificateForm.jsx
Labels: enhancement

#392 Refactor code for consistency and readability
  bsc-js-backend/src/auth/auth.controller.ts
  bsc-js-backend/src/auth/guards/roles.guard.ts
  bsc-js-backend/src/auth/jwt.strategy.ts
  bsc-js-backend/src/main.ts
  bsc-js-backend/src/modules/appointment/appointment.controller.ts
  bsc-js-backend/src/modules/document-applications/document-applications.controller.ts
  bsc-js-backend/src/modules/document-applications/document-applications.service.ts
  bsc-js-backend/src/modules/document-applications/entities/application-status-history.entity.ts
  bsc-js-backend/src/modules/document-applications/entities/document-application.entity.ts
  bsc-js-backend/src/modules/document-applications/services/minio.service.ts
  bsc-js-backend/src/modules/queue/queue.controller.ts
  bsc-js-backend/src/modules/queue/queue.gateway.ts
  bsc-js-backend/src/modules/queue/queue.service.ts
  bsc-js-backend/src/modules/queue/queues.controller.ts
  bsc-js-backend/src/users/dto/create-user.dto.ts
  bsc-js-backend/src/users/dto/paginated-users-response.dto.ts
  bsc-js-backend/src/users/dto/update-user-status.dto.ts
  bsc-js-backend/src/users/dto/user-query.dto.ts
  bsc-js-backend/src/users/dto/user-response.dto.ts
  bsc-js-backend/src/users/dto/user-stats-response.dto.ts
  bsc-js-backend/src/users/users.controller.spec.ts
  bsc-js-backend/src/users/users.controller.ts
  bsc-js-backend/src/users/users.module.ts
  bsc-js-backend/src/users/users.service.spec.ts
  bsc-js-backend/src/users/users.service.ts
  bsc-js-backend/test/jest-setup-e2e.ts
  bsc-js-backend/test/jest-setup.ts
Labels: enhancement, backend

#397 Refactor Marriage Certificate and License application styles for impr…
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/FileUpload.css
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/MarriageCertificateApplication.css
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/MarriageCertificateApplication.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/MarriageDashboard.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/MarriageLicenseApplication.css
Labels: enhancement

#399 Increase document_category column length to 250 characters
  bsc-js-backend/src/modules/document-applications/entities/document-file.entity.ts
  database/modified-document-applications-table-062725-v14/Dump20250627_Modified_Document_Applications_Table_V2.sql
Labels: bug, backend

#401 Enhance document applications functionality by adding support for retrieving all application files for privileged users; update file retrieval logic to return the latest file per category; improve logging for better traceability.
  bsc-js-backend/src/modules/document-applications/document-applications.controller.ts
  bsc-js-backend/src/modules/document-applications/document-applications.service.ts
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminApplicationComponents/AdminFIlePreview.css
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminApplicationComponents/AdminFilePreview.jsx
  bulak-smart-connect-js/src/services/documentApplicationService.js
Labels: enhancement, backend, frontend

#402 application and appointment search
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminApplicationComponents/AdminApplicationDetails.jsx
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminAppointmentDashboard/AllAppointmentAdmin.css
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminAppointmentDashboard/AllAppointmentsAdmin.jsx
Labels: enhancement

#403 removed sample
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/FileUpload.jsx
Labels: enhancement

#406 Refactor password validation and queue number generation
  bsc-js-backend/generate-hash.js
  bsc-js-backend/src/auth/auth.service.ts
  bsc-js-backend/src/modules/queue/queue.service.ts
  bsc-js-backend/test/user-updates.e2e-spec.ts
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AccountManagementComponents/AdminAddAccount.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/SignUpComponents/SignUpForm.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/UserAccountSettings/UserAccount.jsx
  bulak-smart-connect-js/src/__tests__/LogInCard.test.jsx
Labels: enhancement, backend, frontend

#404 admin modifications
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminApplicationComponents/AdminApplicationDetails.css
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminApplicationComponents/AdminApplicationDetails.jsx
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminApplicationComponents/ApplicationAdminDashboard.css
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminApplicationComponents/ApplicationAdminDashboard.jsx
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminApplicationComponents/ApplicationPieChart.jsx
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminAppointmentDashboard/AdminAppointmentDashboard.css
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminAppointmentDashboard/AllAppointmentAdmin.css
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminDashboard/AdminDashboard.jsx
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminDashboard/RecentApplicationsAdmin.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/MarriageLicenseApplication.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/AppointmentComponents/QrCodeAppointment.css
  bulak-smart-connect-js/src/UserBulakSmartConnect/WalkInComponents/WalkInDetails.jsx
Labels: enhancement

#408 Multiple Modifications
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminApplicationComponents/AdminApplicationDetails.jsx
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminAppointmentDashboard/AllAppointmentAdmin.css
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminAppointmentDashboard/AllAppointmentsAdmin.jsx
  bulak-smart-connect-js/src/LandingPageComponents/LandingPage.css
  bulak-smart-connect-js/src/LandingPageComponents/PhTimeComponent.css
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/MarriageCertificateForm/HusbandForm.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/MarriageCertificateForm/MarriageCertificateForm.css
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/MarriageCertificateForm/MarriageCertificateForm.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/MarriageCertificateForm/WifeForm.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/MarriageLicenseApplication.css
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/MarriageLicenseApplication.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/WalkInComponents/WalkInDetails.jsx
Labels: enhancement

#412 Remove default storage prefix from environment configurations
  FRONTEND_SETUP_GUIDE.md
  README.md
  bulak-smart-connect-js/.env.example
  bulak-smart-connect-js/.env.production.example
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminAccount/AdminAccount.jsx
  bulak-smart-connect-js/src/config/env.js
Labels: bug, frontend

#414 Restrict access to manual daily reset and pending count for privileged users
  bsc-js-backend/src/modules/queue/queue.controller.ts
Labels: bug, enhancement, backend
