Repository YuKARLO15/Bulak-Smart-Connect-JS, pull requests merged in 2025-04, with the labels that each got.

#134 merge Yu2 to main
  bsc-js-backend/.firebaserc
  bsc-js-backend/firebase.json
  bsc-js-backend/src/auth/auth.controller.ts
  bsc-js-backend/src/auth/auth.service.ts
  bsc-js-backend/src/auth/dto/login.dto.ts
  bsc-js-backend/src/auth/dto/register.dto.ts
  bsc-js-backend/src/auth/jwt-auth.guard.ts
  bsc-js-backend/src/auth/jwt.strategy.ts
  bsc-js-backend/src/config/database.config.ts
  bsc-js-backend/src/main.ts
  bsc-js-backend/src/users/entities/user.entity.ts
  bsc-js-backend/src/users/users.module.ts
Labels: enhancement, backend

#137 Dashboard and landing page same but with authentication fuction
  bulak-smart-connect-js/src/App.jsx
  bulak-smart-connect-js/src/LandingPageComponents/LandingPage.jsx
  bulak-smart-connect-js/src/LogInComponents/LogIn.jsx
  bulak-smart-connect-js/src/LogInComponents/NavBar.jsx
  bulak-smart-connect-js/src/UserDashboard/NavBar.jsx
Labels: enhancement, frontend

#140 Co-authored-by: YuKARLO15 <YuKARLO15@users.noreply.github.com>
  bulak-smart-connect-js/src/App.jsx
  bulak-smart-connect-js/src/ApplicationComponents/ApplicationContent.jsx
  bulak-smart-connect-js/src/ApplicationComponents/MarriageCertificateApplications/MarriageCertificateForm/HusbandForm.jsx
  bulak-smart-connect-js/src/ApplicationComponents/MarriageCertificateApplications/MarriageCertificateForm/MarriageCertificateForm.css
  bulak-smart-connect-js/src/ApplicationComponents/MarriageCertificateApplications/MarriageCertificateForm/MarriageCertificateForm.jsx
  bulak-smart-connect-js/src/ApplicationComponents/MarriageCertificateApplications/MarriageCertificateForm/MarriageDetailsForm.jsx
  bulak-smart-connect-js/src/ApplicationComponents/MarriageCertificateApplications/MarriageCertificateForm/WifeForm.jsx
Labels: enhancement, frontend

#141 ManageAccount draft
  bulak-smart-connect-js/src/AdminBulakSmart/AdminManageAccount.css
  bulak-smart-connect-js/src/AdminBulakSmart/AdminManageAccount.jsx
  bulak-smart-connect-js/src/AdminBulakSmart/AdminManagementPage/UploadProfilePicture/ProfileUpload.css
  bulak-smart-connect-js/src/AdminBulakSmart/AdminManagementPage/UploadProfilePicture/ProfileUpload.jsx
  bulak-smart-connect-js/src/App.jsx
Labels: enhancement, frontend

#142 Walkin components
  bulak-smart-connect-js/src/App.jsx
  bulak-smart-connect-js/src/LogInComponents/NavBar.jsx
  bulak-smart-connect-js/src/UserDashboard/NavBar.jsx
  bulak-smart-connect-js/src/WalkInComponents/WalkInDashBoard.jsx
  bulak-smart-connect-js/src/WalkInComponents/WalkInDetails.css
  bulak-smart-connect-js/src/WalkInComponents/WalkInDetails.jsx
  bulak-smart-connect-js/src/WalkInComponents/WalkInForm.css
  bulak-smart-connect-js/src/WalkInComponents/WalkInForm.jsx
  bulak-smart-connect-js/src/WalkInComponents/WalkInQueue.css
  bulak-smart-connect-js/src/WalkInComponents/WalkInQueueList.jsx
Labels: enhancement, frontend

#143 merge Yu2 to main
  bsc-js-backend/src/auth/auth.controller.ts
  bsc-js-backend/src/auth/auth.service.ts
  bulak-smart-connect-js/src/SignUpComponents/ContactInformation.jsx
  bulak-smart-connect-js/src/SignUpComponents/FullName.jsx
  bulak-smart-connect-js/src/SignUpComponents/SignUpForm.jsx
  bulak-smart-connect-js/src/services/api.js
Labels: enhancement, backend, frontend

#144 Yu2 to main
  bulak-smart-connect-js/src/App.jsx
  bulak-smart-connect-js/src/ApplicationComponents/BirthCertificateApplications/FirstNameCorrection.jsx
  bulak-smart-connect-js/src/AppointmentComponents/QRCodeAppointment.jsx
  bulak-smart-connect-js/src/SignUpComponents/UserNamePassword.jsx
Labels: bug, frontend

#145 UserManagement per component draft2
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AccountManagementComponents/AccountManagement.css
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AccountManagementComponents/AccountManagement.jsx
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AccountManagementComponents/ProfileUpload.css
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AccountManagementComponents/ProfileUpload.jsx
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AccountManagementComponents/SearchAdd.css
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AccountManagementComponents/SearchAdd.jsx
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AccountManagementComponents/UserTable.css
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AccountManagementComponents/UserTable.jsx
  bulak-smart-connect-js/src/App.jsx
Labels: enhancement, frontend

#150 merge Yu2 to main
  README.md
  database/intial-db-041325-v1/Dump20250413.sql
Labels: documentation, backend

#158 birth back identifications, form validations
  bulak-smart-connect-js/package-lock.json
  bulak-smart-connect-js/package.json
  bulak-smart-connect-js/src/App.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/BirthApplicationSummary.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/BirthCertificateForm.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/BirthCertificateForm/BirthBackIdentifyingForm.css
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/BirthCertificateForm/BirthBackIdentifyingForm.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/BirthCertificateForm/ChildIdentifyingForm.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/BirthCertificateForm/FatherIdentifyingForm.css
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/BirthCertificateForm/FatherIdentifyingForm.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/BirthCertificateForm/MotherIdentifyingForm.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/BirthCertificateForm/PdfGenerator.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/BirthCertificateForm/birth-certificate-template.png
Labels: enhancement, frontend

#161 Astria
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/MarriageCertificateForm/HusbandForm.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/MarriageCertificateForm/MarriageAffidavitForm.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/MarriageCertificateForm/MarriageCertificateForm.css
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/MarriageCertificateForm/MarriageCertificateForm.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/MarriageCertificateForm/WifeForm.jsx
Labels: enhancement

#163 Add Marriage Affidavit Form and integrate into Marriage Certificate w…
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/MarriageCertificateForm/MarriageAffidavitForm.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/MarriageCertificateForm/MarriageCertificateForm.css
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/MarriageCertificateForm/MarriageCertificateForm.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/MarriageCertificateForm/MarriageSummaryForm.jsx
Labels: enhancement, frontend

#167 Yu2
  bulak-smart-connect-js/src/App.jsx
  bulak-smart-connect-js/src/LandingPageComponents/LandingPage.jsx
  bulak-smart-connect-js/src/LogInComponents/LogIn.jsx
  bulak-smart-connect-js/src/LogInComponents/LogInCard.jsx
  bulak-smart-connect-js/src/NavigationComponents/NavBar.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/NavSide.jsx
  bulak-smart-connect-js/src/components/PrivateRoute.jsx
  bulak-smart-connect-js/src/context/AuthContext.jsx
  bulak-smart-connect-js/src/main.jsx
Labels: enhancement, frontend

#173 Admin Add Announcement Draft
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminAnnouncementComponents/AdminAnnouncement.css
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminAnnouncementComponents/AdminAnnouncement.jsx
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminAnnouncementComponents/AnnouncementFeed.css
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminAnnouncementComponents/AnnouncementFeed.jsx
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminAnnouncementComponents/AnnouncementForm.css
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminAnnouncementComponents/AnnouncementForm.jsx
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminAnnouncementComponents/AnnouncementPost.css
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminAnnouncementComponents/AnnouncementPost.jsx
  bulak-smart-connect-js/src/App.jsx
Labels: enhancement, frontend

#176 CTC Birth Certificate Form and upload.
  bulak-smart-connect-js/src/App.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/BirthCertificateDashboard.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/BirthCertificateForm/CopyBirthCertificate.css
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/BirthCertificateForm/CopyBirthCertificate.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/CTCBirthCertificate.css
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/CTCBirthcertificate.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/MarriageCertificateForm/MarriageAffidavitForm.jsx
Labels: enhancement, frontend

#178 Refactor Marriage Certificate Forms: Enhance validation and improve U…
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/MarriageCertificateForm/HusbandForm.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/MarriageCertificateForm/MarriageAffidavitForm.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/MarriageCertificateForm/MarriageCertificateForm.css
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/MarriageCertificateForm/MarriageCertificateForm.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/MarriageCertificateForm/MarriageSummaryForm.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/MarriageCertificateForm/WifeForm.jsx
Labels: enhancement

#179 Cooy birth cert request summary done
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/BirthApplicationSummary.css
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/BirthApplicationSummary.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/BirthCertificateForm/CopyBirthCertificate.css
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/BirthCertificateForm/CopyBirthCertificate.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/CTCBirthcertificate.jsx
Labels: enhancement

#181 read only affidavit summary (user)
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/BirthApplicationSummary.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/BirthCertificateForm/BirthBackIdentifyingForm.css
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/BirthCertificateForm/BirthBackIdentifyingForm.jsx
Labels: enhancement, frontend

#182 Enhance Marriage Certificate Forms: Implement localStorage for form d…
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/MarriageCertificateForm/MarriageAffidavitForm.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/MarriageCertificateForm/MarriageCertificateForm.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/MarriageCertificateForm/MarriageSummaryForm.jsx
Labels: enhancement, frontend

#183 Requirement List
  bulak-smart-connect-js/src/App.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/ApplicationContent.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/BirthCertificateDashboard.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/CorrectionChildSex.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/RequirementBirthList.css
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/RequirementBirthList.jsx
Labels: enhancement, frontend

#189 merge Yu2 to main
  README.md
  bulak-smart-connect-js/src/App.jsx
  bulak-smart-connect-js/src/LogInComponents/LogIn.jsx
  bulak-smart-connect-js/src/LogInComponents/LogInCard.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/NavSide.jsx
  bulak-smart-connect-js/src/components/PrivateRoute.jsx
  bulak-smart-connect-js/src/components/Unauthorized.css
  bulak-smart-connect-js/src/components/Unauthorized.jsx
  bulak-smart-connect-js/src/context/AuthContext.jsx
  database/fixed-saadminstaff-passhash-042225-v3/Dump20250422_Fixed_SAAdminStaff_PassHash.sql
Labels: enhancement, backend

#191 Astria
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminAppointmentDashboard/AdminAppointmentDashboard.css
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminAppointmentDashboard/AdminAppointmentDashboard.jsx
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminDashboard/AdminDashboard.css
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminDashboard/AdminDashboard.jsx
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminWalkInDetails/AdminWalkInDetails.css
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminWalkInDetails/AdminWalkInDetails.jsx
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminWalkInQueue/AdminWalkInQueue.css
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminWalkInQueue/AdminWalkInQueue.jsx
Labels: enhancement

#193 Fixed User Roles Navigation
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminDashboard/AdminDashboard.jsx
  bulak-smart-connect-js/src/LogInComponents/LogIn.jsx
  bulak-smart-connect-js/src/LogInComponents/LogInCard.jsx
  bulak-smart-connect-js/src/context/AuthContext.jsx
Labels: bug, frontend

#194 Add user information display in AdminDashboard component
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminDashboard/AdminDashboard.jsx
Labels: enhancement, frontend

#195 minor edits user side
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminApplicationComponents/ApplicationAdminDashboard.jsx
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminAppointmentDashboard/AdminAppointmentDashboard.jsx
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminDashboard/AdminDashboard.jsx
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminWalkInDetails/AdminWalkInDetails.jsx
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminWalkInQueue/AdminWalkInQueue.jsx
  bulak-smart-connect-js/src/App.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/ApplicationContent.css
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/ApplicationContent.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/BirthCertificateDashboard.css
  bulak-smart-connect-js/src/UserBulakSmartConnect/AppointmentComponents/QRCodeAppointment.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/AppointmentComponents/QrCodeAppointment.css
Labels: enhancement, frontend

#198 working admin add accounts
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AccountManagementComponents/AccountManagement.css
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AccountManagementComponents/AccountManagement.jsx
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AccountManagementComponents/AdminAddAccount.jsx
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AccountManagementComponents/NewUserInfo.js
Labels: enhancement
