Repository YuKARLO15/Bulak-Smart-Connect-JS, pull requests merged in 2025-07, with the labels that each got.

#420 Add OTP functionality for email verification and password reset
  BACKEND_SETUP_GUIDE.md
  bsc-js-backend/.env.example
  bsc-js-backend/.env.production.example
  bsc-js-backend/package-lock.json
  bsc-js-backend/package.json
  bsc-js-backend/src/app.module.ts
  bsc-js-backend/src/auth/auth.controller.ts
  bsc-js-backend/src/auth/auth.module.ts
  bsc-js-backend/src/auth/auth.service.ts
  bsc-js-backend/src/auth/dto/register.dto.ts
  bsc-js-backend/src/entities/otp.entity.ts
  bsc-js-backend/src/services/email.service.ts
  bsc-js-backend/src/services/otp.service.ts
  bulak-smart-connect-js/src/App.jsx
  bulak-smart-connect-js/src/LogInComponents/ForgotPassword.css
  bulak-smart-connect-js/src/LogInComponents/ForgotPassword.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/SignUpComponents/SignUpForm.jsx
  bulak-smart-connect-js/src/components/OTPTest.jsx
  bulak-smart-connect-js/src/components/OTPVerification.css
  bulak-smart-connect-js/src/components/OTPVerification.jsx
  bulak-smart-connect-js/src/services/otpService.js
  database/create-otp-table-063025-v15/Dump20250630_Create_OTP_Table.sql
Labels: enhancement, backend, frontend

#423 feat: Clear sessionStorage on successful registration in SignUpForm
  bulak-smart-connect-js/src/UserBulakSmartConnect/SignUpComponents/SignUpForm.jsx
Labels: enhancement, frontend

#429 Add queue notification functionality with email alerts for position updates and status changes
  bsc-js-backend/src/auth/auth.controller.ts
  bsc-js-backend/src/auth/dto/queue-notification.dto.ts
  bsc-js-backend/src/services/email.service.ts
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminWalkInQueue/AdminWalkInQueue.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/WalkInComponents/WalkInDashBoard.jsx
  bulak-smart-connect-js/src/services/queueNotificationService.js
Labels: enhancement, backend, frontend

#434 Enhance queue notifications, user email retrieval, and password change process
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminAccount/AdminAccount.jsx
  bulak-smart-connect-js/src/LogInComponents/LogInCard.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/UserAccountSettings/UserAccount.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/WalkInComponents/WalkInDashBoard.jsx
  bulak-smart-connect-js/src/services/queueNotificationService.js
Labels: enhancement, frontend

#435 modified file upload
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/BirthCertificateForm.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/CorrectionClericalError.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/DelayedBelow18.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/DelayedOneParentForeigner.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/DelayedOutOfTown.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/FirstNameCorrection.jsx
Labels: enhancement

#437 Add appointment notification service and enhance email handling
  bsc-js-backend/src/auth/auth.controller.ts
  bsc-js-backend/src/auth/dto/appointment-notification.dto.ts
  bsc-js-backend/src/services/email.service.ts
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminAppointmentDashboard/AllAppointmentsAdmin.jsx
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AppointmentDetailsComponents/AppointmentDetails.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/AppointmentComponents/AppointmentContent.jsx
  bulak-smart-connect-js/src/services/appointmentNotificationService.js
Labels: enhancement, backend, frontend

#439 appointment modification, marriage file upload fixed
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/ApplicationContent.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/CorrectionChildSex.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/RequirementBirthList.css
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/RequirementBirthList.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/RequirementBirthListSample.css
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/MarriageCertificateApplication.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/MarriageLicenseApplication.css
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/MarriageLicenseApplication.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/AppointmentComponents/AppointmentDashboard.css
  bulak-smart-connect-js/src/UserBulakSmartConnect/AppointmentComponents/AppointmentDashboard.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/AppointmentComponents/RecentAppointment.css
  bulak-smart-connect-js/src/UserBulakSmartConnect/AppointmentComponents/RecentAppointment.jsx
Labels: enhancement

#442 enhance user contact information handling in application forms and se…
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminApplicationComponents/AdminApplicationDetails.css
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminApplicationComponents/AdminApplicationDetails.jsx
  bulak-smart-connect-js/src/App.jsx
  bulak-smart-connect-js/src/NavigationComponents/NavBar.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/BirthCertificateForm.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/BirthCertificateForm/CopyBirthCertificate.css
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/BirthCertificateForm/CopyBirthCertificate.jsx
  bulak-smart-connect-js/src/services/documentApplicationService.js
Labels: enhancement

#445 Enhance appointment fetching and email handling
  bsc-js-backend/src/modules/appointment/appointment.controller.ts
  bsc-js-backend/src/modules/appointment/appointment.service.ts
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminAppointmentDashboard/AllAppointmentsAdmin.jsx
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AppointmentDetailsComponents/AppointmentDetails.jsx
  bulak-smart-connect-js/src/services/appointmentService.js
Labels: enhancement, backend, frontend

#449 Implement document application notification system
  bsc-js-backend/src/auth/auth.controller.ts
  bsc-js-backend/src/modules/document-applications/document-applications.controller.ts
  bsc-js-backend/src/modules/document-applications/document-applications.service.ts
  bsc-js-backend/src/services/email.service.ts
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminApplicationComponents/AdminApplicationDetails.jsx
  bulak-smart-connect-js/src/services/documentApplicationNotificationService.js
  bulak-smart-connect-js/src/services/documentApplicationService.js
Labels: enhancement, backend, frontend

#448 media query
  bulak-smart-connect-js/src/LandingPageComponents/LandingPage.css
  bulak-smart-connect-js/src/LandingPageComponents/LandingPage.jsx
  bulak-smart-connect-js/src/LogInComponents/LogIn.css
  bulak-smart-connect-js/src/LogInComponents/LogInCard.css
  bulak-smart-connect-js/src/LogInComponents/LogInContent.css
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/DelayedAbove18.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/AppointmentComponents/AppointmentDashboard.css
  bulak-smart-connect-js/src/footer.css
  bulak-smart-connect-js/src/footer.jsx
Labels: enhancement

#453 Add progress indicators to BirthCertificateForm and clean up DelayedO…
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/BirthCertificateForm.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/DelayedOutOfTown.jsx
Labels: enhancement

#457 Enhance application status update with detailed notifications and logging
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminApplicationComponents/AdminApplicationDetails.jsx
Labels: enhancement, frontend

#459 Enhance application submission process with confirmation email notifications
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/CorrectionChildSex.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/DelayedAbove18.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/DelayedBelow18.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/DelayedOneParentForeigner.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/DelayedOutOfTown.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/FirstNameCorrection.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/MarriageCertificateApplication.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/MarriageLicenseApplication.jsx
Labels: enhancement, frontend

#460 Luan
  bulak-smart-connect-js/src/App.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/MarriageCertificateForm/MarriageAffidavitForm.css
  bulak-smart-connect-js/src/UserBulakSmartConnect/NotificationComponent/CustomStatusNotification.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/NotificationComponent/UserNotification.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/NotificationComponent/notification.jsx
  bulak-smart-connect-js/src/services/notificationContext.jsx
Labels: enhancement

#464 MODIFICATIONS
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/CorrectionChildSex.css
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/CorrectionChildSex.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/CorrectionClericalError.css
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/CorrectionClericalError.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/DelayedBelow18.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/DelayedOutOfTown.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/FirstNameCorrection.css
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/FirstNameCorrection.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/NotificationComponent/UserNotification.jsx
Labels: enhancement

#466 Update application title and configure React Scan feature
  FRONTEND_SETUP_GUIDE.md
  bulak-smart-connect-js/.env.example
  bulak-smart-connect-js/.env.production.example
  bulak-smart-connect-js/src/config/env.js
  bulak-smart-connect-js/src/main.jsx
Labels: enhancement, frontend

#469 Enhance logging with NestJS Logger integration
  BACKEND_SETUP_GUIDE.md
  bsc-js-backend/.env.example
  bsc-js-backend/.env.production.example
  bsc-js-backend/src/auth/auth.controller.ts
  bsc-js-backend/src/auth/auth.service.ts
  bsc-js-backend/src/main.ts
  bsc-js-backend/src/modules/appointment/appointment.service.ts
  bsc-js-backend/src/modules/document-applications/document-applications.controller.ts
  bsc-js-backend/src/modules/document-applications/document-applications.service.ts
  bsc-js-backend/src/modules/queue/queue.controller.ts
  bsc-js-backend/src/modules/queue/queue.service.ts
  bsc-js-backend/src/modules/queue/queues.controller.ts
  bsc-js-backend/src/services/email.service.ts
  bsc-js-backend/src/users/users.controller.ts
  bsc-js-backend/src/users/users.service.ts
Labels: enhancement, backend

#472 Update README to include Docker in Additional Technologies
  README.md
Labels: documentation, enhancement

#474 Enhance production security and performance with middleware
  bsc-js-backend/package-lock.json
  bsc-js-backend/package.json
  bsc-js-backend/src/main.ts
  bulak-smart-connect-js/vite.config.js
Labels: enhancement, backend, frontend

#476 Add Aiven MySQL SSL configuration to environment files and app module
  BACKEND_SETUP_GUIDE.md
  bsc-js-backend/.env.example
  bsc-js-backend/.env.production.example
  bsc-js-backend/src/app.module.ts
Labels: enhancement, frontend

#477 Merge latest changes to production
  BACKEND_SETUP_GUIDE.md
  README.md
  bsc-js-backend/.env.example
  bsc-js-backend/.env.production.example
  bsc-js-backend/src/app.module.ts
Labels: deployment

#488 Fix Cloudflare R2 integration by adding required MinIO client configu…
  bsc-js-backend/src/main.ts
  bsc-js-backend/src/modules/document-applications/services/minio.service.spec.ts
  bsc-js-backend/src/modules/document-applications/services/minio.service.ts
  bsc-js-backend/src/services/minio.service.ts
Labels: deployment

#491 Improve MinIO connection check handling
  bsc-js-backend/src/main.ts
Labels: bug, backend

#493 Refactor health check to improve service checks
  README.md
  bsc-js-backend/src/main.ts
Labels: bug, backend

#495 Modified pages for media query
  bulak-smart-connect-js/src/LandingPageComponents/FloatingAnnouncement.css
  bulak-smart-connect-js/src/NavigationComponents/NavBar.css
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/BirthApplicationSummary.css
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/BirthApplicationSummary.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/NotificationComponent/CustomStatusNotification.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/WalkInComponents/WalkInForm.css
Labels: enhancement

#498 Set MINIO_ENABLE_PORT to false in production environment configuration
  bsc-js-backend/.env.production.example
Labels: documentation, backend

#499 Production Again
  BACKEND_SETUP_GUIDE.md
  bsc-js-backend/.env.example
  bsc-js-backend/.env.production.example
  bsc-js-backend/src/app.module.ts
  bsc-js-backend/src/auth/auth.service.ts
  bsc-js-backend/src/main.ts
  bsc-js-backend/src/modules/appointment/appointment.service.ts
  bsc-js-backend/src/modules/document-applications/document-applications.service.ts
  bsc-js-backend/src/modules/document-applications/services/minio.service.spec.ts
  bsc-js-backend/src/modules/document-applications/services/minio.service.ts
  bsc-js-backend/src/modules/queue/queue.controller.ts
  bsc-js-backend/src/services/email.service.ts
  bsc-js-backend/src/services/minio.service.spec.ts
  bsc-js-backend/src/services/minio.service.ts
  bsc-js-backend/src/users/users.controller.ts
  bulak-smart-connect-js/src/LandingPageComponents/FloatingAnnouncement.css
  bulak-smart-connect-js/src/NavigationComponents/NavBar.css
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/BirthApplicationSummary.css
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/BirthApplicationSummary.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/NotificationComponent/CustomStatusNotification.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/WalkInComponents/WalkInForm.css
Labels: deployment

#500 Add MINIO_ENABLE_PORT configuration to README
  README.md
Labels: documentation

#496 Enhance BirthCertificateForm and IdentifyingForm CSS for improved res…
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/BirthCertificateDashboard.css
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/BirthCertificateDashboard.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/BirthCertificateForm.css
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/BirthCertificateForm/ChildIdentifyingForm.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/BirthCertificateForm/IdentifyingForm.css
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/RequirementBirthList.css
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/RequirementBirthListSample.css
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/MarriageCertificateForm/MarriageSummaryForm.css
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/MarriageCertificateForm/MarriageSummaryForm.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/RequirementMarriageList.css
  bulak-smart-connect-js/src/UserBulakSmartConnect/AppointmentComponents/RequirementDeathList.css
  bulak-smart-connect-js/src/UserBulakSmartConnect/AppointmentComponents/RequirementDeathList.jsx
Labels: enhancement

#501 Enhance AdminWalkInQueue and LogInCard components with improved UI el…
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminWalkInQueue/AdminWalkInQueue.css
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminWalkInQueue/AdminWalkInQueue.jsx
  bulak-smart-connect-js/src/LogInComponents/LogInCard.css
  bulak-smart-connect-js/src/LogInComponents/LogInCard.jsx
Labels: enhancement

#504 Fix typo in background image URL for LogIn component
  bulak-smart-connect-js/src/LogInComponents/LogIn.css
Labels: enhancement, frontend

#506 Adjust NavBar CSS for improved responsiveness and button sizing
  bulak-smart-connect-js/src/NavigationComponents/NavBar.css
Labels: enhancement

#507 Enhance PWA installation process with improved debugging and automatic prompt display
  bulak-smart-connect-js/src/components/InstallPrompt.jsx
  bulak-smart-connect-js/src/hooks/usePWA.js
  bulak-smart-connect-js/src/main.jsx
Labels: bug, frontend

#510 Enhanced PWA Service Workers
  bulak-smart-connect-js/package.json
  bulak-smart-connect-js/public/_headers
  bulak-smart-connect-js/public/sw-handler.js
  bulak-smart-connect-js/scripts/build-hook.js
  bulak-smart-connect-js/src/App.jsx
  bulak-smart-connect-js/src/components/UpdateNotification.jsx
  bulak-smart-connect-js/src/hooks/usePWA.js
  bulak-smart-connect-js/src/main.jsx
  bulak-smart-connect-js/src/utils/version.js
  bulak-smart-connect-js/vite.config.js
Labels: deployment

#513 Enhance caching strategy in service worker for images
  bulak-smart-connect-js/vite.config.js
Labels: enhancement, frontend

#515 Refactor password hashing for improved security
  bsc-js-backend/src/auth/auth.service.ts
  bsc-js-backend/src/users/users.controller.ts
Labels: enhancement, backend

#517 Changes before Defense
  bsc-js-backend/src/auth/auth.service.ts
  bsc-js-backend/src/users/users.controller.ts
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminAnnouncementComponents/AnnouncementForm.css
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminAnnouncementComponents/AnnouncementForm.jsx
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminAnnouncementComponents/AnnouncementPost.css
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminAnnouncementComponents/EditAnnouncementModal.css
  bulak-smart-connect-js/src/NavigationComponents/NavSide.jsx
Labels: deployment

#522 Update branding from "Bulak LGU Smart Connect" to "Bulak LGU Connect"
  .github/workflows/update-dashboard.yml
  README.md
  bsc-js-backend/src/auth/auth.controller.spec.ts
  bsc-js-backend/src/auth/auth.controller.ts
  bsc-js-backend/src/modules/queue/queue.controller.spec.ts
  bsc-js-backend/src/modules/queue/queue.gateway.spec.ts
  bsc-js-backend/src/services/email.service.spec.ts
  bsc-js-backend/src/services/email.service.ts
  bulak-smart-connect-js/index.html
  bulak-smart-connect-js/src/LandingPageComponents/LandingPage.jsx
  bulak-smart-connect-js/src/LandingPageComponents/LandingPageAssets/BulakLGULogo.png
  bulak-smart-connect-js/src/LogInComponents/LogInContent.jsx
  bulak-smart-connect-js/src/NavigationComponents/NavAssets/NavBulakLGU.png
  bulak-smart-connect-js/src/UserBulakSmartConnect/TermsAndConditionComponents/TermsAndCondition.jsx
  bulak-smart-connect-js/src/components/InstallPrompt.jsx
  bulak-smart-connect-js/src/hooks/usePWA.js
Labels: deployment

#525 Production Minor Patch
  .github/workflows/accessibility-testing.yml
  .github/workflows/api-documentation.yml
  .github/workflows/api-security.yaml
  .github/workflows/backend-tests.yml
  .github/workflows/browser-compatibility.yml
  .github/workflows/ci.yml
  .github/workflows/code-quality-security.yml
  .github/workflows/codeql.yml
  .github/workflows/dependency-security-scan.yml
  .github/workflows/frontend-documentation.yml
  .github/workflows/mysql-ci.yml
  bsc-js-backend/src/auth/auth.controller.spec.ts
  bsc-js-backend/src/auth/auth.service.ts
  bsc-js-backend/src/modules/queue/queue.controller.spec.ts
  bsc-js-backend/src/services/email.service.spec.ts
  bsc-js-backend/src/users/users.controller.ts
  bsc-js-backend/test/jest-setup-e2e.ts
  bulak-smart-connect-js/src/UserBulakSmartConnect/AppointmentComponents/AppointmentContent.jsx
Labels: deployment

#526 Panel Minor revisions
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminApplicationComponents/AdminApplicationDetails.css
  bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminApplicationComponents/AdminApplicationDetails.jsx
  bulak-smart-connect-js/src/UserBulakSmartConnect/WalkInComponents/WalkInForm.css
  bulak-smart-connect-js/src/UserBulakSmartConnect/WalkInComponents/WalkInForm.jsx
Labels: enhancement
